# Generated by Django 5.1.7 on 2025-03-14 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FirstVariantBd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_object', models.CharField(max_length=255)),
                ('department', models.CharField(max_length=255)),
                ('competentions', models.TextField(blank=True, null=True)),
                ('profile', models.CharField(blank=True, max_length=255, null=True)),
                ('test_obj', models.CharField(blank=True, max_length=50, null=True)),
                ('exam', models.CharField(blank=True, max_length=50, null=True)),
                ('control_work', models.CharField(blank=True, max_length=50, null=True)),
                ('test_obj_with_mark', models.CharField(blank=True, max_length=50, null=True)),
                ('course_work', models.CharField(blank=True, max_length=50, null=True)),
                ('course_project', models.CharField(blank=True, max_length=50, null=True)),
                ('essay', models.CharField(blank=True, max_length=50, null=True)),
                ('calcul_analytic_work', models.CharField(blank=True, max_length=50, null=True)),
                ('creative_homework', models.CharField(blank=True, max_length=50, null=True)),
                ('project_work', models.CharField(blank=True, max_length=50, null=True)),
                ('classroom_hours', models.IntegerField(blank=True, null=True)),
                ('lectures', models.IntegerField(blank=True, null=True)),
                ('seminars', models.IntegerField(blank=True, null=True)),
                ('independent_work', models.IntegerField(blank=True, null=True)),
                ('ECTS', models.FloatField(blank=True, null=True)),
                ('total_hours', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Планы',
                'verbose_name_plural': 'Планы',
            },
        ),
    ]
