# Generated by Django 5.1.7 on 2025-03-14 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='firstvariantbd',
            name='direction_of_preparation',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='firstvariantbd',
            name='edu_program',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='firstvariantbd',
            name='scientific_speciality',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
