# Generated by Django 5.1.7 on 2025-03-27 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_firstvariantbd_direction_of_preparation_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Description_of_competencies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('competency_name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Компетенции',
                'verbose_name_plural': 'Компетенции',
            },
        ),
    ]
